version: '3'

services:
  db:
    image:
      postgres:13.3-alpine
    env_file:
      - .env
    expose:
      - 5432
    restart:
      always
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      bash -c "flask init-db
      && gunicorn app.run:app --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart:
      always
    volumes:
      - app_logs:/todo-app/logs
    depends_on:
      - db

volumes:
  db_data:
  app_logs:
