DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tasks;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR (32) UNIQUE NOT NULL,
    email VARCHAR (64) UNIQUE NOT NULL,
    hashed_password VARCHAR (512) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id  SERIAL PRIMARY KEY,
    title VARCHAR (32) UNIQUE NOT NULL,
    description VARCHAR (128) NOT NULL,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users (id)
);
